# Generated by Django 5.2.4 on 2026-06-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20260610_0830"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="github",
        ),
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="user",
            name="github_url",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=124),
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(default="", max_length=124),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=124, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="images/default-avatar.png", upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=12),
        ),
    ]
