# Generated by Django 5.2.4 on 2026-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
